version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:3000"
    # Uncomment to save db between sessions
    # volumes:
    #   - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: commands-encoding-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
# uncomment to expose and map port to db on host
#ports:
# - "5433:5432" # map port to something different than default 5432
# Uncomment to save db between sessions on host system
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# Uncomment to save db between sessions on host system
# volumes:
#   postgres-db:
